### ISSUE TITLE
Refresh Token capability to TPP

### ISSUE THREAD

**Issue by chaitanya14** [Venafi/terraform-provider-venafi#103]
**BUSINESS PROBLEM**
At present, our access token expires for every 90 days and we end up creating a new token and update the token. 

**PROPOSED SOLUTION**
Add refresh_token and client_id to the provider config and generate venafi config using the refreshToken and clientId and let venafi [sdk](https://github.com/Venafi/vcert/blob/240fe8ff3ae0a85b998804665cc7f1400ea6b210/pkg/venafi/tpp/connector.go#L154
) do its work.
https://github.com/Venafi/terraform-provider-venafi/pull/102

**CURRENT ALTERNATIVES**
Generate token for every 90 days and update the access_token.

**VENAFI EXPERIENCE**
We have been using since a year.

**Comment by brental** [comment]
Similar to #25 and #105 this issue seems like it would be handled by the venafi-token provider and a venafi-token_credential resource. Could it also be closed?

**Comment by brental** [comment]
@luispresuelVenafi Can this be closed similar to #25 ?

**Comment by luispresuelVenafi** [comment]
Yes @brental , this has been resolved as well now that we have [Terraform Token Provider](https://github.com/Venafi/terraform-provider-venafi-token). I'm closing this issue
