### ISSUE TITLE
Adding O, OU, S, L to the certificate object

### ISSUE THREAD

**Issue by ATFromB** [Venafi/terraform-provider-venafi#108]
**BUSINESS PROBLEM**

Requesting for O, OU, S, L to the certificate object to be added to terraform, as the "recommended settings" are not configured for all "Issuing templates" as we have set value for O, OU, S, L to the certificate object which is requiring us to double up and reapply these values to "recommended settings"

**PROPOSED SOLUTION**

Requesting for O, OU, S, L to the certificate object to be added for the terraform option rather than only replying on "recommended settings"

**CURRENT ALTERNATIVES**

Manually editing each template to add "recommended settings" 

**VENAFI EXPERIENCE**

1 year +

**Comment by bones108** [comment]
It appears that we are experiencing this issue as well ... can we get this prioritized?  Here is a sample of errors we are receiving:

│ Error: vcert error: server error: Unexpected status code on Venafi Cloud zone read. Status: 412 Precondition Failed
│ Error Code: 10726 Error: Distinguished name component O with value "" is invalid
│ Error Code: 10726 Error: Distinguished name component L with value "" is invalid
│ Error Code: 10726 Error: Distinguished name component ST with value "" is invalid
│ Error Code: 10726 Error: Distinguished name component C with value "" is invalid

**Comment by marcos-albornoz** [comment]
> It appears that we are experiencing this issue as well ... can we get this prioritized? Here is a sample of errors we are receiving:
> 
> │ Error: vcert error: server error: Unexpected status code on Venafi Cloud zone read. Status: 412 Precondition Failed │ Error Code: 10726 Error: Distinguished name component O with value "" is invalid │ Error Code: 10726 Error: Distinguished name component L with value "" is invalid │ Error Code: 10726 Error: Distinguished name component ST with value "" is invalid │ Error Code: 10726 Error: Distinguished name component C with value "" is invalid

Hi @bones108 , I think you are facing a different issue because the original comment on this thread is more to request an enhancement to avoid to repeat to set the recommend settings on each one of issuing templates in Control Plane.

Did you configure the [recommended settings in your issuing template?](https://github.com/Venafi/terraform-provider-venafi?tab=readme-ov-file#venafi-control-plane)  :-)
