### ISSUE TITLE
Add Retire function to Terraform Provider

### ISSUE THREAD

**Issue by brysow-Venafi** [Venafi/terraform-provider-venafi#117]
**BUSINESS PROBLEM**
Currently the terraform provider that integrates with TPP does not allow for a retire function related to Terraform destroy. As certificates are being requested via the terraform provider, a lack of this function means that certificates that are no longer in use after a resource is destroyed are being monitored and licensed within Venafi Trust Protection Platform.

**PROPOSED SOLUTION**
Add a retire function to the terraform provider so that terraform destroy calls can leverage this to retire the certificate in Venafi Trust Protection Platform
Environment is Venafi Trust Protection Platform 22.4.6

**CURRENT ALTERNATIVES**
Manual methods to retire the certificate have to be used. The team would rather the provider handle this versus create a scripted method.

**VENAFI EXPERIENCE**
This is being filed on behalf of a TPP customer who has been using Venafi Trust Protection Platform for several years.

**Comment by jeffwhite06** [comment]
+1

**Comment by luispresuelVenafi** [comment]
Closing this issue as it has been resolved by [version 0.18.0](https://github.com/Venafi/terraform-provider-venafi/releases/tag/v0.18.0)
