### ISSUE TITLE
isn't going to be Official terraform provider ?

### ISSUE THREAD

**Issue by zerolaser** [Venafi/terraform-provider-venafi#12]
Hey folks, This is not an issue. Just wondering if this provider will be officially added to the list of terraform providers ?

**Comment by tr1ck3r** [comment]
Yes @zerolaser, we are currently working through the approval process with HashiCorp.

**Comment by zerolaser** [comment]
@tr1ck3r with terraform 0.12.0 released out. any update on this ?

**Comment by tr1ck3r** [comment]
Our Terraform provider has been approved by HashiCorp and is now being maintained at https://github.com/terraform-providers/terraform-provider-venafi.  Version 0.8.0 added support for Terraform 0.12 back in July, apologies for not commenting on that in this issue sooner.
