### ISSUE TITLE
Update requirement doco to include PBE algorithm requirements for TPP service generated CSRs

### ISSUE THREAD

**Issue by brental** [Venafi/terraform-provider-venafi#125]
**BUSINESS PROBLEM**
The Trust Protection Platform [requirements](https://github.com/Venafi/terraform-provider-venafi?tab=readme-ov-file#venafi-trust-protection-platform) do not mention PBE algorithm requirements for service generated CSRs. It is not currently made clear that the PBE algorithm should be configured for either "SHA1 3DES" or "SHA256 AES256" for service generated CSRs to work and the error message returned when it is not set to those does not make it clear what the issue is.

**PROPOSED SOLUTION**
Update TPP requirements documentation to mention that for service generated CSRs to work the PBE algorithm should be configured for either "SHA1 3DES" or "SHA256 AES256" as per
https://github.com/Venafi/terraform-provider-venafi/issues/91#issuecomment-1109930265

**CURRENT ALTERNATIVES**
Upgrading PBE algorithm to be configured for either "SHA1 3DES" or "SHA256 AES256". However, need the doco updated so people know they should do this.

**VENAFI EXPERIENCE**
6 months experience using TPP and the terraform provider.

**Comment by luispresuelVenafi** [comment]
Not sure if this should be placed here since this is not an actual Terraform issue, rather a missing documentation within TLSPDC (f.k.a TPP).

**Comment by luispresuelVenafi** [comment]
Hi @brental ,

If there's an expecific page which do you believe it should have this info, in the TPP docs, could you look down for the link below and click it?

![image](https://github.com/Venafi/terraform-provider-venafi/assets/77068025/7050d5dc-0de9-43cc-862a-adc282ad852b)


It will autogenerate the an email with pre-populated data in order for you to let us know which page would like to have that the improvement for, and will populate much other information for you.

If you don't have an specific page suggestion, it's ok, sending that email with the pre-populated email and the information you expect will help the TPP docs team to enable that information.

Since this is not an issue for this Open Source tool I'll be closing this ticket.

**Comment by brental** [comment]
hey @luispresuelVenafi, I do think this is an issue in the documentation for this terraform provider. In the README for this repo under [Venafi Trust Protection Platform](https://github.com/Venafi/terraform-provider-venafi?tab=readme-ov-file#venafi-trust-protection-platform) it has the following:

![image](https://github.com/Venafi/terraform-provider-venafi/assets/10455806/537acd98-7af7-46ff-a5df-ca7e584ebf33)

The highlighted section lists policies that should be applied to folders in order for this provider to work. The provider requires a PBE algorithm of either "SHA1 3DES" or "SHA256 AES256" to work when using service generated CSR's but that requirement is not included in the highlighted list. So, I think this issue should be re-opened as it does relate to the documentation for this terraform provider.

**Comment by brental** [comment]
@luispresuelVenafi ^^^

**Comment by brental** [comment]
This is another example that shows Venafi aren't interested in properly monitoring and responding to GitHub issues.

**Comment by luispresuelVenafi** [comment]
Hi Brental,

sorry for the delay in response.

That requirements section was initially mostly set to help the user to set a quick start. Service generated was not considered a regular type of mode to be used, hence what I mentioned above. After another look with my managers, we decided to also include what you mentioned above

**Comment by luispresuelVenafi** [comment]
Hi @brental ,

sorry for the delay in response.

That requirements section was initially mostly set to help the user to set a quick start. Service generated was not considered a regular type of mode to be used, hence what I mentioned above. After another look with my team, we decided to also include what you mentioned above

**Comment by luispresuelVenafi** [comment]
Hi @brental ,

We just attended this issue with your requested doc update, I'll be closing it accordingly :smile:
