### ISSUE TITLE
Certificate is not matching key

### ISSUE THREAD

**Issue by raymondhardynike** [Venafi/terraform-provider-venafi#15]
When i use terraform provider to get a certificate it gives a key missmatch

The file below is an example of what i am using there have been some value changes to protect test data but the format remains the same

`````
provider "venafi" {
    url = "https://ven.venafi.com"
    tpp_username = "test_user"
    tpp_password = "secret"
    trust_bundle = "${file("bundle.pem")}"
    zone = "\\example\\Internal"
}

resource "venafi_certificate" "example_cert" {
    common_name = "isvenafiworking.example.com"
    algorithm = "RSA"
    rsa_bits = "2048"
}

output "cert_certificate" {
    value = "${venafi_certificate.example_cert.certificate}"
}

output "cert_chain" {
    value = "${venafi_certificate.example_cert.chain}"
}

output "cert_private_key" {
    value = "${venafi_certificate.example_cert.private_key_pem}"
}
`````

When i use openssl verify on it i get 
server.crt: CN = isvenafiworking.example.com
error 20 at 0 depth lookup:unable to get local issuer certificate

The modulus of the key and the certificate are not the same

however when i use vcert to generate the same certificate everything works as expected

Terraform v0.11.11
terraform-provider-venafi_0.4-alpha_darwin.zip

**Comment by arykalin** [comment]
Hi @raymondhardynike is this certificate already present in TPP when you trying to enroll it?

**Comment by arykalin** [comment]
Hi again @raymondhardynike , could you try latest 6.0 release? https://github.com/Venafi/terraform-provider-venafi/releases/tag/0.6.0

**Comment by raymondhardynike** [comment]
Yes this is a certificate that exists already vcert 

0.6.0 still has the same issue

#:~/workspace/venafi-test% openssl x509 -noout -modulus -in server.crt | openssl md5
10fc0aa39fbac53ba594f1c4b4eeeda9
#:~/workspace/venafi-test% openssl rsa -noout -modulus -in server.key| openssl md5
d0183584c18232911999f18d66138b58

When i use vcert i use the enroll option to get the same certificate and the key and cert do match.

However the certificate and the key from terraform are not the same as what i get from vcert as well. I don't know how terraform is getting this invalid certificate at all.

**Comment by arykalin** [comment]
Hi @raymondhardynike is it possible that terraform didn't change anything and you get the same certificate which you've got with 0.4? Could you try to run terrafrom destroy and then terraform apply again. Also could you show the status of "terraform state show"? You can send it to opensource@venafi.com

**Comment by arykalin** [comment]
Hi @raymondhardynike @zerolaser
Please try new release 6.1 (https://github.com/Venafi/terraform-provider-venafi/releases/tag/0.6.1) It should fix your issue.

**Comment by raymondhardynike** [comment]
Something is broken in that build and terraform does not see it as a provider
https://pastebin.com/qXmKusmE

**Comment by raymondhardynike** [comment]
I compiled from master and it renews the certificate even if it is a valid certificate. This makes the terraform run take a long time then time out.

In working with venafi api on another project what i ended up doing to solve this was 3 verifications. First i check to see if the current certificate is valid. If it is not valid i pull a certificate and validate that. if that is not valid i renew.

**Comment by tr1ck3r** [comment]
@raymondhardynike would you please confirm the version of Trust Protection Platform you are using?  We're currently working on an issue that affects 18.4 in the way that you've described.  It should not be possible to retrieve the previous certificate using POST Certificates/Retrieve after a new request has been successfully submitted using POST Certificates/Request or POST Certificates/Renew.

**Comment by raymondhardynike** [comment]
Yes it is 18.4

**Comment by arykalin** [comment]
@raymondhardynike to make plugin work you need o rename the plugin binary according terraform naming convention, like it said in https://github.com/Venafi/terraform-provider-venafi#download-and-install-the-venafi-provider-plugin. Rename terraform-provider-venafi_0.6.1+117_darwin86 to terraform-provider-venafi_0.6.1

**Comment by arykalin** [comment]
> I compiled from master and it renews the certificate even if it is a valid certificate. This makes the terraform run take a long time then time out.
> 
> In working with venafi api on another project what i ended up doing to solve this was 3 verifications. First i check to see if the current certificate is valid. If it is not valid i pull a certificate and validate that. if that is not valid i renew.

Currently we support only terraform create operation, and working on update operation. Behavior you described is implemented in our ansible solution, maybe you can try it - https://github.com/Venafi/ansible-role-venafi

**Comment by raymondhardynike** [comment]
@arykalin The update behavior is not needed at this time it is mostly the timeout issue that is the problem. I am looking to use terraform as it is what we use in the rest of the pipeline.

**Comment by arykalin** [comment]
@raymondhardynike Could you clarify, did you try latest binary release? Did it fix the problem with key mismatch?
Also, could you clarify this comment "I compiled from master and it renews the certificate even if it is a valid certificate." you mean the problem is that if you have certificate in TPP but don't have it in terraform state terraform will request a new certificate with same certificate DN and it will take a long time? This one is the timeout issue?

**Comment by arykalin** [comment]
Issuer should be fixed in latest release.
