### ISSUE TITLE
Add ability to specify "Service-Generated" Private Key & Certificate Signing Request (CSR)

### ISSUE THREAD

**Issue by Xeleema** [Venafi/terraform-provider-venafi#20]
**BUSINESS PROBLEM**

Security-conscious customers (such as myself) would be able to specify "Service-Generated" instead of "User-Generated".
This will cause the Private Key and CSR to be generated by TPP instead of locally.

**PROPOSED SOLUTION**

Ability to specify "Service-Generated", while still defaulting to "User-Generated" would preserve the current expected behavior, but would permit a more secure option for those customers that wish to do so.

**CURRENT ALTERNATIVES**

Forking this provider and adding these options ourselves.

**VENAFI EXPERIENCE**

Daily for 8 months.

**Comment by tr1ck3r** [comment]
@Xeleema supporting service generated key pairs is on our roadmap but won't happen this year unless it is contributed by the community.  We've identified two use cases where service generated keys have value over local (VCert) generated keys:  1️⃣ to enable TLS traffic inspection which requires private keys for decryption, and 2️⃣ to maximize entropy by leveraging an HSM to generate exportable keys (Venafi Advanced Key Protect).  Locally generated keys are advantageous in that they adhere to the security best practice of minimizing key exposure (i.e. keys should only exist where they are required).

We welcome and encourage third party contributions to our open source projects so please consider submitting a pull request if you implement this feature so the entire Venafi customer community can benefit.

**Comment by luispresuelVenafi** [comment]
I'm closing this issue, since it has been addressed in  [v0.14.0](https://github.com/Venafi/terraform-provider-venafi/releases/tag/v0.14.0)
