### ISSUE TITLE
Add linters to build process to validate that code follows recommended Go coding style

### ISSUE THREAD

**Issue by lhdomenech** [Venafi/terraform-provider-venafi#26]
Code in this repository differs from recommend Go coding style as described by [https://golang.org/doc/effective_go.html](Effective Go).

[golangci-lint](https://github.com/golangci/golangci-lint) integrates with the most popular Go linters so it can validates that the code follows recommended coding style. Ideally this would be integrated in the build process and PR checks.

**Comment by tr1ck3r** [comment]
Thank you @lhdomenech We're using `golangci-lint` for [VCert Go](https://github.com/Venafi/vcert) and I agree with your recommendation to apply it to this project as well.

**Comment by luispresuelVenafi** [comment]
I'm closing this issue since `golangci-lint` already forms part of the project's most recent versions.
