### ISSUE TITLE
Is Read/Renew/Update/Delete possible

### ISSUE THREAD

**Issue by gani247** [Venafi/terraform-provider-venafi#29]
Can I use current release to Read a cert using `data` as we do with terraform+aws provider. And is Renew/delete/update possible now.

**Comment by arykalin** [comment]
Hi @gani247 Yes, you can read certificate, look for examples in Makefile under test_e2e_* actions. Also up on read checkForRenew function will be called which will check certificate against expiration_window option - https://github.com/Venafi/terraform-provider-venafi#creating-a-certificate-and-private-key-pair
Delete operation is not implemented yet.

**Comment by gani247** [comment]
I've set of certs created before, can I mange them now like renewing/read...

**Comment by gani247** [comment]
Closing
