### ISSUE TITLE
failing at :Terraform Import 

### ISSUE THREAD

**Issue by gani247** [Venafi/terraform-provider-venafi#30]
When trying to import existing certificate using Terraform getting below error

`
$ terraform import venafi_certificate.web_venafi_example cxx90xxx-xxxx-xxxx-xxxx-559xxxx3bxx8
venafi_certificate.web_venafi_example: Importing from ID "cxx90xxx-xxxx-xxxx-xxxx-559xxxx3bxx8
"...

Error: venafi_certificate.web_venafi_example (import id: cxx90xxx-xxxx-xxxx-xxxx-559xxxx3bxx8
): import venafi_certificate.web_venafi_example (id: cxx90xxx-xxxx-xxxx-xxxx-559xxxx3bxx8
): resource venafi_certificate doesn't support import
`

**Comment by tr1ck3r** [comment]
Hi @gani247, that error message is accurate.  The current implementation of our Terraform provider does not support the `import` method.  Can you please describe your use case?  Is it for renewing an existing certificate?  If so, is there a reason that you wouldn't be able to request a new certificate with the same subject and SANs?

**Comment by gani247** [comment]
Exactly... I'm trying to renew a existing one.
Can you share the reason...why the current implementation don't support ?

**Comment by gani247** [comment]
thanks!
