### ISSUE TITLE
Is using "data", "null_resource" possible?

### ISSUE THREAD

**Issue by gani247** [Venafi/terraform-provider-venafi#32]
like 

`
data "venafi_certificate" "webserver-cert" {
  ........
}
`
to get existing cert info
and 
`
resource "null_resource" "webserver-cert"  {
  .......
}
`
are above scenarios possible with the current implementation?

**Comment by arykalin** [comment]
Hi @gani247 as I understand null_resource should be supported by any terraform provider. If not please open an issue.
