### ISSUE TITLE
Terraform PLAN Renewing the certificate

### ISSUE THREAD

**Issue by gani247** [Venafi/terraform-provider-venafi#34]
I was trying to PLAN, but Terraform renewed my certificate.

I know that cert reached its expiration-window, but my intention was to PLAN not to RENEW.

on PLAN i could see the cert-logs in Venafi which modified the serial number.

**Comment by arykalin** [comment]
Hi @gani247 Hmm, it was intentional. Though I agree that not clear. Let me think how fix it.

**Comment by gani247** [comment]
any solution to this?

**Comment by gani247** [comment]
its just PLANing, if I use default values for all properties (for ex: expiration_window: 168)

**Comment by arykalin** [comment]
Yes, sorry that, I'll create a fix as soon as possible.

**Comment by gani247** [comment]
@arykalin any update here?

**Comment by arykalin** [comment]
@gani247 sorry, didn't find a solution for this yet. Terraform is checking of updated during read operation which is running on both update and renew. The reason for that is that we wanted to update certificate even if apply called on already created certificate. Because in this case only read operation is performed. Unfortunately I forgot that read operation is called on plan too.

**Comment by gani247** [comment]
You know where exactly the problem is, what stopping you actually...  I can help you... in standardizing the solution.
...............
We have a huge requirement with this provider.

**Comment by gani247** [comment]
@arykalin .. plz help me understand `checkForRenew` method in  `resource_venafi_certificate.go`.

**Comment by mr-tron** [comment]
For example if your certificate expiring 05 Jun 16:30 and renew window is 24 hour, it should be renewed if you run terraform after 04 Jun 16:30. This functions checks this condition. Is expiring time closer than renew window allows.

**Comment by gani247** [comment]
@arykalin any update here, on this issue?

its a show-stopper for us now. so if you can give the time-line we will plan accordingly.

**Comment by gani247** [comment]
@arykalin .. any fix on this issue?

**Comment by mr-tron** [comment]
We fixed issue. You can compile from branch by your self https://github.com/Venafi/terraform-provider-venafi/tree/fix-refresh-on-planning  or waiting merging to master. It can require some time. May be in Monday.

**Comment by mr-tron** [comment]
It doesn`t tested  - our testing infrastructure is unavailable in this moment. So on your risk.

**Comment by gani247** [comment]
Good to hear that...!!

**Comment by gani247** [comment]
@mr-tron .... i hope test goes well today....... !!

**Comment by tr1ck3r** [comment]
@gani247 yes, it should be soon.  Venafi Cloud is planning to release a major update later today and that will allow us to release a new version of VCert and then new releases for all of its downstream consumers including this project.

**Comment by mr-tron** [comment]
https://github.com/Venafi/terraform-provider-venafi/releases/tag/0.7.0
Sorry for waiting

**Comment by gani247** [comment]
Great to see this.... Thanks for your prompt responses...!
