### ISSUE TITLE
Incompatible API version with plugin

### ISSUE THREAD

**Issue by zosocanuck** [Venafi/terraform-provider-venafi#35]
Getting the following error when running `terraform plan`

> Error: Failed to instantiate provider "venafi" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

```
provider "venafi" {
    url = "https://xxx/vedsdk"
    tpp_username = "xxxx"
    tpp_password = "xxxxx"
    zone = "DevOps"
}

# Define a Venafi certificate resource
resource "venafi_certificate" "webserver" {
    common_name = "service1.contoso.com"
    algorithm = "ECC"
    rsa_bits = "2048"
    san_dns = [
        "www.contoso.com",
        "www2.contoso.com",
	"service1.contoso.com"
    ]
#    key_password = "passw0rd"
}
```

Environment:
- Terraform v0.12.1
- terraform-provider-venafi 0.6.3

**Comment by mr-tron** [comment]
https://github.com/Venafi/terraform-provider-venafi/tree/master-ven-50144-update-terraform-version

**Comment by karthikpappu** [comment]
thank you
