### ISSUE TITLE
Support for Import existing venafi_certificate resource

### ISSUE THREAD

**Issue by rangarb885** [Venafi/terraform-provider-venafi#48]
**BUSINESS PROBLEM**
We have lot of certificates in Venafi. We want to automate the process to manage them via terraform. First step on this is to import the existing certificates to terraform state. Unfortunately this resource does not support importer yet.

```Error: resource venafi_certificate doesn't support import```

**PROPOSED SOLUTION**
Add support for Import existing venafi_certificate resource to state file

**CURRENT ALTERNATIVES**
None

**VENAFI EXPERIENCE**
2 years, 6months via Terraform.

**Comment by fcatacut** [comment]
Is this closed by PR #73 and included in [v0.15.0](https://github.com/Venafi/terraform-provider-venafi/releases/tag/v0.15.0)?

**Comment by luispresuelVenafi** [comment]
@fcatacut Yes, it is. I'm closing this now since ithas been adressed in [v0.15.0](https://github.com/Venafi/terraform-provider-venafi/releases/tag/v0.15.0)
