### ISSUE TITLE
PLAN failing at expiration window value

### ISSUE THREAD

**Issue by gani247** [Venafi/terraform-provider-venafi#6]
Getting below error while updating certificate. I created a cert with 8784 hours of window time. but while updating its i got below one.

Error: Error refreshing state: 1 error(s) occurred:

* module.venafi-acm.venafi_certificate.cert: 1 error(s) occurred:

* module.venafi-acm.venafi_certificate.cert: venafi_certificate.cert: certificate validity duration 8783h59m59s is less than configured expiration window 8784h0m0s

**Comment by arykalin** [comment]
Hi @gani247 could you show your terraform plan?

**Comment by tr1ck3r** [comment]
@gani247 were you able to resolve your issue?

**Comment by tr1ck3r** [comment]
No response.  This seems to be working as designed... the `expiration_window` must be less than or equal to the validity of the issued certificate--in this case it was 1 second less.  We've included a 1 day buffer so using an `expiration_window` of 8783 would achieve the desired result (i.e. the certificate would always be renewed when the plan was applied).  The intent with the `expiration_window` is to prevent unnecessary certificate renewals (i.e. the existing certificate is far from expiring so continue using it).
