### ISSUE TITLE
Error asking for user input: 1 error(s) occurred

### ISSUE THREAD

**Issue by karthick9500** [Venafi/terraform-provider-venafi#6]
Error: Error asking for user input: 1 error(s) occurred:

* provider.venafi: plugin exited before we could connect

Karthicks-MacBook-Air:venafi karthickv$ TF_LOG=DEBUG terraform plan
2018/10/20 23:20:12 [INFO] Terraform version: 0.11.7
2018/10/20 23:20:12 [INFO] Go runtime version: go1.10.1
2018/10/20 23:20:12 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.7/bin/terraform", "plan"}
2018/10/20 23:20:12 [DEBUG] Attempting to open CLI config file: /Users/karthickv/.terraformrc
2018/10/20 23:20:12 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/10/20 23:20:12 [INFO] CLI command args: []string{"plan"}
2018/10/20 23:20:12 [INFO] command: empty terraform config, returning nil
2018/10/20 23:20:12 [DEBUG] command: no data state file found for backend config
2018/10/20 23:20:12 [DEBUG] New state was assigned lineage "d0d50eaa-2730-eb4f-a2cf-02c342593a4d"
2018/10/20 23:20:12 [INFO] command: backend initialized: <nil>
2018/10/20 23:20:12 [DEBUG] checking for provider in "."
2018/10/20 23:20:12 [DEBUG] checking for provider in "/usr/local/Cellar/terraform/0.11.7/bin"
2018/10/20 23:20:12 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2018/10/20 23:20:12 [DEBUG] checking for provider in "/Users/karthickv/.terraform.d/plugins"
2018/10/20 23:20:12 [WARN] found legacy provider "terraform-provider-ibm"
2018/10/20 23:20:12 [WARN] found legacy provider "terraform-provider-venafi"
2018/10/20 23:20:12 [DEBUG] found valid plugin: "venafi", "0.0.0", "/Users/karthickv/.terraform.d/plugins/terraform-provider-venafi"
2018/10/20 23:20:12 [DEBUG] found valid plugin: "ibm", "0.0.0", "/Users/karthickv/.terraform.d/plugins/terraform-provider-ibm"
2018/10/20 23:20:12 [DEBUG] checking for provisioner in "."
2018/10/20 23:20:12 [DEBUG] checking for provisioner in "/usr/local/Cellar/terraform/0.11.7/bin"
2018/10/20 23:20:12 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2018/10/20 23:20:12 [DEBUG] checking for provisioner in "/Users/karthickv/.terraform.d/plugins"
2018/10/20 23:20:12 [INFO] command: backend <nil> is not enhanced, wrapping in local
2018/10/20 23:20:12 [INFO] backend/local: starting Plan operation
2018/10/20 23:20:12 [INFO] terraform: building graph: GraphTypeInput
2018/10/20 23:20:12 [DEBUG] Resource state not found for "venafi_csr.webserver": venafi_csr.webserver
2018/10/20 23:20:12 [TRACE] Graph after step *terraform.AttachStateTransformer:

venafi_csr.webserver - *terraform.NodeAbstractResource
2018/10/20 23:20:12 [TRACE] Graph after step *terraform.RootVariableTransformer:

venafi_csr.webserver - *terraform.NodeAbstractResource
2018/10/20 23:20:12 [DEBUG] resource venafi_csr.webserver using provider provider.venafi
2018/10/20 23:20:12 [DEBUG] ReferenceTransformer: "venafi_csr.webserver" references: []
2018/10/20 23:20:12 [DEBUG] ReferenceTransformer: "provider.venafi" references: []
2018-10-20T23:20:12.225+0400 [DEBUG] plugin: starting plugin: path=/Users/karthickv/.terraform.d/plugins/terraform-provider-venafi args=[/Users/karthickv/.terraform.d/plugins/terraform-provider-venafi]
2018-10-20T23:20:12.231+0400 [DEBUG] plugin: waiting for RPC address: path=/Users/karthickv/.terraform.d/plugins/terraform-provider-venafi
2018-10-20T23:20:12.477+0400 [DEBUG] plugin.terraform-provider-venafi: 2018/10/20 23:20:12 Error executing vcert: exit status 2
2018-10-20T23:20:12.482+0400 [DEBUG] plugin: plugin process exited: path=/Users/karthickv/.terraform.d/plugins/terraform-provider-venafi
2018/10/20 23:20:12 [ERROR] root: eval: *terraform.EvalInitProvider, err: plugin exited before we could connect
2018/10/20 23:20:12 [ERROR] root: eval: *terraform.EvalSequence, err: plugin exited before we could connect

2018/10/20 23:20:12 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error asking for user input: 1 error(s) occurred:

* provider.venafi: plugin exited before we could connect

**Comment by arykalin** [comment]
Hi @karthick9500 could you try latest version?

**Comment by tr1ck3r** [comment]
@karthick9500 were you able to resolve your issue?

**Comment by arykalin** [comment]
@karthick9500 please check latest release and reopen the issue if problem persists.

**Comment by awahnteh** [comment]
Problem Persists. I just tried it myself and got the same error. More specific error messages would also be helpful
