### ISSUE TITLE
Support for zone / folder and policy creation

### ISSUE THREAD

**Issue by mbrancato** [Venafi/terraform-provider-venafi#8]
**BUSINESS PROBLEM**
We are trying to automate onboarding

**PROPOSED SOLUTION**
Support creation of zones / folders and the associated attributes with this provider.

**CURRENT ALTERNATIVES**
scripts, etc.

**VENAFI EXPERIENCE**
4 months, every day

**Comment by tr1ck3r** [comment]
@mbrancato thank you for your idea.  It sounds like you are looking for a new Venafi resource that can be used by a Venafi administrator to configure Venafi policy, is that right?  As opposed to the current resource which is intended more for managing the lifecycle of certificates needed by infrastructure deployed using Terraform.

**Comment by mbrancato** [comment]
Yes @tr1ck3r - if I could compare it to the Vault provider, that provider can be both a Vault client as well as a way to configure Vault.

I do think it requires a new resource, etc.

**Comment by marshallford** [comment]
I'm also interested in this functionality. Alternately, I wish creating a certificate via the API would just create any zones/folders missing in the path (similar to the behavior of Vault or even `mkdir -p foo/bar/baz`).
